/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI Document on Azure Functions
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CandidateRegistration
 */
export interface CandidateRegistration {
    /**
     * 
     * @type {number}
     * @memberof CandidateRegistration
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof CandidateRegistration
     */
    company?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidateRegistration
     */
    user?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidateRegistration
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidateRegistration
     */
    phone?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidateRegistration
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidateRegistration
     */
    attachment?: string;
}

/**
 * Check if a given object implements the CandidateRegistration interface.
 */
export function instanceOfCandidateRegistration(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CandidateRegistrationFromJSON(json: any): CandidateRegistration {
    return CandidateRegistrationFromJSONTyped(json, false);
}

export function CandidateRegistrationFromJSONTyped(json: any, ignoreDiscriminator: boolean): CandidateRegistration {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'company': !exists(json, 'company') ? undefined : json['company'],
        'user': !exists(json, 'user') ? undefined : json['user'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'phone': !exists(json, 'phone') ? undefined : json['phone'],
        'url': !exists(json, 'url') ? undefined : json['url'],
        'attachment': !exists(json, 'attachment') ? undefined : json['attachment'],
    };
}

export function CandidateRegistrationToJSON(value?: CandidateRegistration | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'company': value.company,
        'user': value.user,
        'email': value.email,
        'phone': value.phone,
        'url': value.url,
        'attachment': value.attachment,
    };
}

