/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI Document on Azure Functions
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CandidateRegistration,
} from '../models';
import {
    CandidateRegistrationFromJSON,
    CandidateRegistrationToJSON,
} from '../models';

export interface CandidateregistrationRequest {
    body?: CandidateRegistration;
}

/**
 * CandidateApi - interface
 * 
 * @export
 * @interface CandidateApiInterface
 */
export interface CandidateApiInterface {
    /**
     * 
     * @param {CandidateRegistration} [body] Json request body containing candidate model details
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CandidateApiInterface
     */
    candidateregistrationRaw(requestParameters: CandidateregistrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>>;

    /**
     */
    candidateregistration(requestParameters: CandidateregistrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string>;

}

/**
 * 
 */
export class CandidateApi extends runtime.BaseAPI implements CandidateApiInterface {

    /**
     */
    async candidateregistrationRaw(requestParameters: CandidateregistrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/candidate`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CandidateRegistrationToJSON(requestParameters.body),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async candidateregistration(requestParameters: CandidateregistrationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.candidateregistrationRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
