/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI Document on Azure Functions
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Contest,
} from '../models';
import {
    ContestFromJSON,
    ContestToJSON,
} from '../models';

export interface GetcontestsbytenantidRequest {
    guid: string;
}

/**
 * ContestApi - interface
 * 
 * @export
 * @interface ContestApiInterface
 */
export interface ContestApiInterface {
    /**
     * 
     * @param {string} guid TenantId.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContestApiInterface
     */
    getcontestsbytenantidRaw(requestParameters: GetcontestsbytenantidRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Contest>>>;

    /**
     */
    getcontestsbytenantid(requestParameters: GetcontestsbytenantidRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Contest>>;

}

/**
 * 
 */
export class ContestApi extends runtime.BaseAPI implements ContestApiInterface {

    /**
     */
    async getcontestsbytenantidRaw(requestParameters: GetcontestsbytenantidRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Contest>>> {
        if (requestParameters.guid === null || requestParameters.guid === undefined) {
            throw new runtime.RequiredError('guid','Required parameter requestParameters.guid was null or undefined when calling getcontestsbytenantid.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/contest/{guid}`.replace(`{${"guid"}}`, encodeURIComponent(String(requestParameters.guid))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ContestFromJSON));
    }

    /**
     */
    async getcontestsbytenantid(requestParameters: GetcontestsbytenantidRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Contest>> {
        const response = await this.getcontestsbytenantidRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
